version: "3.8"

services:
    main:
        command: [ "/project/docker/main.sh" ]
        build:
          context: .
          dockerfile: Dockerfile
        container_name: "parser"
        environment:
          - MONGODB_URL=mongodb://mongo_db
        networks:
          - custom
    db:
      container_name: "mongo_db"
      image: mongo
      restart: on-failure
      ports:
        - "27017:27017"
      volumes:
        - /var/lib/mongodb/:/data/db
      networks:
        - custom
networks:
  custom:
    driver: bridge